name: 'Update Fonts'
on:
  push:
    branches:
      - master

jobs:
  update-fonts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules
      - run: yarn
      - run: |
          npx tsx ./src/fetch-list.ts
          npx tsx ./src/download-fonts.ts
          npx tsx ./src/generate-css.ts
      - run: |
          git config user.email namorzyny@gmail.com
          git config user.name Namorzyny
          git add .
          git commit -m "Update to version: `node -p "require('./package.json').version"`" || echo 'Nothing was commited.'
          git push
